repos:
- repo: https://github.com/pycqa/pylint
  rev: v2.13.8
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
    args:
      [
        "-rn", # Only display messages
        "--rcfile=pyproject.toml",
      ]
