name: pre-commit-on-pr-branch

on:
  pull_request:

jobs:
  pre-commit-on-pr-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34.3.4
      - name: diff files print
        run: echo ${{ steps.changed-files.outputs.all_changed_files }}
      - name: install pylint
        run: pip install pylint
      - name: pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --files ${{ steps.changed-files.outputs.all_changed_files }}
